# bibliotheca

## leipzig

### dnb

#### ausgeliehen

- Goldsmith, *Unkreatives Schreiben* (trans. 2017)


- Die Lochkarten-Buchhaltungs-Maschinen meines Systems / Gustav Tauschek, [Wien, XIV., Meinhartsdorfergasse 1] : [G. Tauschek], 1930. [dnb](http://d-nb.info/576641979)
- Gustav Tauschek und seine Maschinen / Martin Helfert ; Petra Mazuran ; Christoph Wintersteiger. Mit einem Geleitw. von Heinz Zemanek, Linz : Trauner, 2006. [dnb](http://d-nb.info/980811902)


- Hessel, *Spazieren in Berlin* (1929)

#### bestellen

- Frank (ed.), Von der systematischen Bibliographie zur Dokumentation (1978) [dnb](http://d-nb.info/790224143) [toc](http://d-nb.info/790224143/04)
- Urbans, Klaus; et al., *Elektrografie. Analoge und digitale Bilder*, Köln: DuMont 1994.
- Saskia Reiter, *Computerpoesie. Studien zur Modifikation poetischer Texte durch den Computer*, Bielefeld: transcript 2003.

#### lesesaal

- Klaus Urbons, *Kopieren heute : d. Geschichte d. Fotokopie u. ihre heutige Anwendung für d. moderne Büro*, Langenhagen: Minolta-Camera-Handelsges., Business Equipment Div. 1988.

```
Museumslesesaal : (LS 7.6 KOP)
Signatur: Nb 96
Lesesaalbestand
```


### albertina

#### bestellt

- *Neue Rundschau* 42.1 (1931)
    -  Roland Kayser, Die Eroberung der Allgegenwärtigkeit, pp. 713f.

#### bestellen

- IID / FID Communicationes
- Theo Lutz, *Grundlagen der Datenverarbeitung : der Computer und seine Möglichkeiten; Lerntext*, Berlin: IBM Deutschland GmbH 1981.

#### ausgeliehen

- Stanisław Lem, *Summa technologiae*, Berlin: Verl. Volk u. Welt 1980.
    - Aus dem Polnischen von Friedrich Griese, (c) Frankfurt am Main: Insel Verl. 1976
- Heinlein, Robert A., *Stranger in a strange land*, 9. impr., New York: Putnam 1961.
- Vonnegut, Kurt. *Das Höllische System*, München: Goldmann, 1988. [albi](https://katalog.ub.uni-leipzig.de/Record/0002511600)
    - 1. ungekürzte dt. Ausg., 1. Aufl. // [albi-eng](https://katalog.ub.uni-leipzig.de/Record/0002347356)


### zwg-bib kunst

- Susan Sontag, *Über Fotografie*
    - Freihandbereich `AP 93450 S699(18)`

### zwg-bib theaterwissenschaft

- Susan Sontag, *Im Zeichen des Saturn*
    - Freihandbereich `91-8-11795`

- *Manuscrits de Hamlet-machine* / Heiner Muller. Transcription de Julia Bernhard. Trad. de Jean Jourdheuil.  Paris : Ed. de Minuit, 2003.
    - Freihandbereich `01A-2005-450`



## berlin

### fu

- *New York Times Magazin*
    - Kelly, *Scan This Book!* (May 14, 2006), pp. 42-49.
    - Kelly, *Becoming Screen Literate*, (Nov. 23, 2008), pp. MM48 (= Sunday Magazine).

```
1896,6.Sept. - 1899,27.Aug.;
1901,2.Jan. - 1919;
1923 -
Signatur:
M 691
Standort:
Untergeschoss Periodika
J.F. Kennedy-Institut
```

[primo](https://fu-berlin.hosted.exlibrisgroup.com/primo-explore/fulldisplay?docid=FUB_ALMA_DS21939232040002883&context=L&vid=FUB&search_scope=FUB_ALL&tab=fub&lang=de_DE)


- *New York Times*
    - Brin, *A Library to Last Forever* (Oct. 8, 2009), pp. A31 (= NY Ed.).

```
Es existieren keine bestellbaren Exemplare.
Bitte wenden Sie sich an die Auskunft.

Signatur:
M 691
Standort:
Untergeschoss Periodika
J.F. Kennedy-Institut

Bestand:
1851 -  [L=2009]
```

[primo](https://fu-berlin.hosted.exlibrisgroup.com/primo-explore/fulldisplay?docid=FUB_ALMA_DS51950788200002883&context=L&vid=FUB&search_scope=FUB_ALL&tab=fub&lang=de_DE)


- *The New Yorker*
    - Janet Flanner, *Goethe in Hollywood* (Dec. 13, 1941), pp. 31ff./(Dec. 20, 1941), pp. 22ff.
    - Toobin, *Google's Moon Shot. The Quest for the Universal Library* (Feb. 5, 2007), pp. 30–35.

```
1.1925 -26.1951
Signatur:
M 765
Standort:
Untergeschoss Periodika
J.F. Kennedy-Institut
```

[primo](https://fu-berlin.hosted.exlibrisgroup.com/primo-explore/fulldisplay?docid=FUB_ALMA_DS21935862030002883&context=L&vid=FUB&search_scope=FUBkat&tab=fub_local&lang=de_DE)


### sbb zeitung

- Die Nationalbibliothek in der Westentasche (1938) [[src](http://stabikat.de/DB=1/XMLPRS=N/PPN?PPN=165994797)]

### sbb udl

- Fidler, *Mediamorphosis, or the Transformation of Newspapers into a New Medium*, in: *Media Studies Journal* (Fall 1991)
- *Ecquid novi : African journalism studies*
    - Issue: *Newspaper of the Future* (1983) Vol. 4, No. 1
        - [editorial](https://doi.org/10.1080/02560054.1983.9652912)

### smb kunst

- Abraham A. Moles, *Erstes Manifest der permutationellen Kunst*, Stuttgart : Walther 1961?
    - Signatur : `NB 30028 - kl 8`
- Klaus Burkhardt; Reinhard Döhl, *poem structures in the looking glass*, Stuttgart : Walther, 1969
    - Signatur: `NB 30028 - kl 40`


## misc

- Paul Valéry, *La cônquete de l’ubiquité*
    - *De la musique avant toute chose*, Paris: Edition du Tambourinaire 1929
        - gibt's in dresden: [Zentralbibliothek: Magazin Musik](https://katalogbeta.slub-dresden.de/id/0006587431/)


- Paul Valéry, *Mes théâtres*
    - [*Les dernières nouvelles*, 19 novembre 1942](https://lccn.loc.gov/sn95058048)
    - [*La NEF*, no. 6, mai 1945](https://zdb-katalog.de/title.xhtml?idn=011193026)

- Susan Sontag, *On Photgraphy* (1977)
    - New York: Farrar, Straus and Giroux, 1977


- Mel Gussow, *Conversations with and about Beckett*
    - Seitenabschnitt! dt./en.


- Rul Gunzenhäuser, *Ein Weihnachtsgedicht*
    - wohl in *Ja und Nein. Unabhängige Jugendzeitschrift* (1960), Nr. 12 und (1961), Nr. 1


- Theodor W. Adorno, *Scientific Experiences of a European Scholar in America* (1968)
    - in: »Perspectives in American History«, Harvard University, Vol. II, 1968.


- Theodor W. Adorno, *Wissenschaftliche Erfahrungen in Amerika*, in: *Neue deutsche Hefte*, Jahrgang 16, Heft 2, Juni 1969, S. 3ff.

- *Direction* 2 (Dec, 1939), No. 8: Special issue on "Exiled German Writers. Art, Fiction, Documentary Material"


- Klaus Mann, *The turning point*, New York: L. B. Fischer 1942.
    - [DNB](http://d-nb.info/1032621397)


- Erika Mann, Klaus Mann: *Escape to Life* (1939)
    - [DNB](http://d-nb.info/1032656859)


- Erika Mann, Klaus Mann: *The other Germany* (1940)
    - [DNB](http://d-nb.info/992581265)


## done

### dnb

- Buchreport (1985), Nr. 18
    - Haefner rät den Verlagen zu einer digitalen Strategie
- Boris Langendorf, *Interview mit Prof. Klaus Haefner: 1987 ist das letzte Jahr ohne Konkurrenz durch das ›elektronische Buch‹*, in *Buchreport* 18 (Jan. 2, 1987), no. 1, p. 7.
- Hansjörg Mayer, *Typoems*, Stuttgart: Studiengalerie, Hahnhochhaus, 1965
- Max Bense, *Theorie der Texte. Eine Einführung in neuere Auffassungen und Methoden*, Cologne and Berlin: Kiepenheuer & Witsch, 1962.
- Ja und Nein. Zeitschrift (1959)
    - in der Weihnachtsnummer: erstes Computer-Gedicht veröffentlicht (Gunzenhäuser?)
- Rolf Lohberg/Theo Lutz, *Was denkt sich ein Elektronengehirn?*, Stuttgart: Franckh'sche Verlagshandlung.
- Automat und Mensch Steinbuch, Karl. - Berlin : Springer, 1961
- Schmidt, Siegfried J., Ästhetische Prozesse
- Grundlagenstudien aus Kybernetik und Geisteswissenschaft (1960)
    - darin wohl: Lutz, Über ein Programm zur Erzeugung stochastisch-logischer Texte
        - Grundlagenstudien 1 (1960), Stuttgart
- *Germanistik - Forschungsstand und Perspektiven* / Teil 2. *Ältere deutsche Literatur, neuere deutsche Literatur* (1985)
    - Kittler, *Literatur und Literaturwissenschaft als Word Processing*, pp. 410-419.
- Leibniz, *De l'horizon de la doctrine humaine* (ed. 1991)
- [@flu20.ged89.ger]
- *Meine Theater* [1942], in: ders.: Werke. Frankfurter Ausgabe, Band 2: Dialoge und Theater, hg. von Karl Alfred Blüher, Frankfurt/M: Insel 1990, pp. 434-439.
- Valery, *Über Kunst* (1959)
- Valery, *Dialoge und Theater* (ed. 1990)
- Nora, *Zwischen Geschichte und Gedächtnis* (1990)
- Nora, *Zwischen Geschichte und Gedächtnis* (1998)
