# persona

## husserl, edmund

Philosophie der Arithmetik (1891)

Dieter Münch, The early work of Edmund Husserl and artificial intelligence, The Journal of the British Society for Phenomenology (1990) 21, 108-120.

ders., Minds, brains and cognitive science, in Armin Burkhardt (ed.), Speech acts, meaning and intentions, Berlin: de Gruyter 1990, 367-390.

## arnheim, rudolf

- Rundfunk als Hörkunst/Radio as Sound (1933/36)

## mendelsohn, erich

- *Amerika: Bilderbuch eines Architekten* (193X)


## bataille, georges

- Bataille, 'Begriff der Verausgabung' (1933)
--> Forderung »nach neuen Medien kollektiver Affizierung« u.a. in 'Ästhetik und Gesellschaft' (stw)

## weizenbaum, joseph

- Eliza (1966)
- Haefner, Weizenbaum im Gespräch, SPIEGEL (1987)

## goldsmith, kenneth

- Wasting Time on the Internet (2016)
    - Prothesengott


## debord, guy



## kittler, friedrich

- Die Stadt ist ein Medium (1988)

## zweig, stefan

- Sternstunden der Menschheit
- The Tide of Fortune: Twelve Historical Miniatures (1940)

## kay, alan

- A Personal Computer for Children of All Ages (1972)

Dynabook

## rinks, josefine

- Josefine Rinks, Serverland (2018)

## andersen, hendrik christian

- *Creation of a World Centre of Communication* (1913)

## bense, max

– Max Bense, Programmierung des Schönen (1960)

## balasz, bela

- Zur Kunstphilosophie des Films (1938)


## warhol, andy

```
Amiga Presentation


Guy Wright, Glenn Suokko, "Andy Warhol: An Artist and His Amiga. A conversation about art and the Amiga with Artist Andy Warhol"
in: AmigaWorld (Jan./Feb. 1986)
Issue 3 (Vol 2 No 1, January 1986 ?
```

## hochstetter, gustav

- [@hoc73.sch13.ger]

## fairthorne, robert

Fairthorne, R. A. (1958). Automatic retrieval of recorded information. Computer Journal, 1: 36-41.

## vonnegut, kurt


- Player Piano (1952)
    - `DEU` Das höllische System

Player Piano is the first novel of American writer Kurt Vonnegut, published in 1952. It depicts a dystopia of automation, describing the negative impact it can have on quality of life. The story takes place in a near-future society that is almost totally mechanized, eliminating the need for human laborers.

## ritter, johann wilhelm

```
Die Physik als Kunst : ein Versuch, die Tendenz der Physik aus ihrer Geschichte zu deuten ; zur Stiftungsfeyer der königlich-baierischen Akademie der Wissenschaften am 28sten März 1806
Autor / Hrsg.: Ritter, Johann Wilhelm ; Ritter, Johann Wilhelm
Verlagsort: München | Erscheinungsjahr: 1806 | Verlag: Lindauer
Signatur: 1404947 4 Bavar. 2132 h-1/5#Cah.3 1404947 4 Bavar. 2132 h-1/5#Cah.3
Reihe: Die Physik als Kunst : ein Versuch, die Tendenz der Physik aus ihrer Geschichte zu deuten ; zur Stiftungsfeyer der königlich-baierischen Akademie der Wissenschaften am 28sten März 1806
Permalink: http://www.mdz-nbn-resolving.de/urn/resolver.pl?urn=urn:nbn:de:bvb:12-bsb10336183-1

Fragmente aus dem Nachlasse eines jungen Physikers : ein Taschenbuch für Freunde der Natur
Autor / Hrsg.: Ritter, Johann Wilhelm ; Ritter, Johann Wilhelm
Verlagsort: Heidelberg | Erscheinungsjahr: (1810) | Verlag: Mohr und Zimmer
Signatur: Phys.g. 379-1
Reihe: Fragmente aus dem Nachlasse eines jungen Physikers : ein Taschenbuch für Freunde der Natur
Permalink: http://mdz-nbn-resolving.de/urn:nbn:de:bvb:12-bsb10131878-4


Fragmente aus dem Nachlasse eines jungen Physikers : ein Taschenbuch für Freunde der Natur
Autor / Hrsg.: Ritter, Johann Wilhelm ; Ritter, Johann Wilhelm
Verlagsort: Heidelberg | Erscheinungsjahr: (1810) | Verlag: Mohr und Zimmer
Signatur: Phys.g. 379-2
Reihe: Fragmente aus dem Nachlasse eines jungen Physikers : ein Taschenbuch für Freunde der Natur
Permalink: http://mdz-nbn-resolving.de/urn:nbn:de:bvb:12-bsb10131879-4
```

## twain, mark

[src](https://history-computer.com/Internet/Dreamers/Twain.html)

The telectrophonoscope of Mark Twain

The great American author Samuel Langhorne Clemens (1835–1910), better known by his pen name Mark Twain, wrote The Adventures of Tom Sawyer and its sequel, Adventures of Huckleberry Finn, the latter often called "the Great American Novel".

Jan SzczepanikIn 1898 Twain met Jan Szczepanik (1872–1926) (see the nearby image), a young and very capable Austrian-Polish inventor, with several hundred patents and over 50 discoveries to his name, many of which are still applied today. Some of Szczepanik's concepts helped the future evolution of TV broadcasting, such as the telectroscope (an apparatus for distant reproduction of images and sound using electricity) or the wireless telegraph, which greatly affected the development of telecommunications. Szczepanik invented also a submarine, a colorimeter, an electric rifle, a color image weaving method, a moving wing aircraft, a duplex rotor helicopter, a dirigible, etc.

The term "telectroscope" was devised by the French writer and publisher Louis Figuier (1819–1894) in 1878 to popularize an invention wrongly interpreted as real and incorrectly ascribed to Alexander Graham Bell. Figuier's "telectroscope" was a fictional device, the first prototype television, capable to transmit pictures and sound anywhere.

Later the word "telectroscope" was widely accepted by several 19th century inventors like George Carey, Constantin Senlecq, Adriano de Paiva, and Jan Szczepanik, who (together with the Viennese banker Ludwig Kleinberg) applied for a British patent for his device (Method and Apparatus for Reproducing Pictures and the like at a Distance by Means of Electricity) in 1897 (British Patent N°5031). Szczepanik's telectroscope was covered in the New York Times in April, 1898, where it was described as a scheme for the transmission of colored rays.

In 1898 Twain described Szczepanik in two of his articles: "The Austrian Edison keeping school again" and "From The Times of 1904".

In the "From The Times of 1904" (it is a fictional criminal short story) Twain dreamed up for a telelectroscope (he called it telectrophonoscope), which used the existing phone system to create a world wide network of information-sharing. In the Twain's short story, as early as in 1904, telectrophonoscopes are spread all over the globe, and every man can get one and exchange visual and sound information with all other owners of telectrophonoscopes.

## freud, sigmund

- [@fre56.not25.ger]

Translation, reprinted from Int. l. Psycho-Anal., 21 (1940), 469, by James Strachey

- [The 'Mystic Writing Pad': What Would Freud Make of Today's Tablets?](https://www.theatlantic.com/technology/archive/2013/01/the-mystic-writing-pad-what-would-freud-make-of-todays-tablets/272512/)

## goldberg, emmanuel

Goldberg, E. (1932b). Das Registrierproblem in der Photographie. In International Congress of Photography. 8th, Dresden, 1931. Bericht über den VIII. Internationalen Kongress fuer Wissenschaftliche und Angewandte Photographie, Dresden, 1931. Herausg. von J. Eggert und A. von Biehler. (317-320). Leipzig: Barth.

Goldberg, Emanuel: Das Registrierproblem in der Photographie. In: Eggert, J./Biehler, A. v. (Hrsg.): Bericht über den VIII. Internationalen Kongress für Wissenschaftliche und Angewandte Photographie : Dresden 1931. Barth/Leipzig 1932. S. 317-320.

Zeiss Ikon AG. & Goldberg, E. (1938). Vorrichtung zum Aussuchen statistischer und Buchhalterischer Angaben. [German] Patentschrift 670 190. Dec. 22, 1938.

Goldberg, N. (1969). The other Goldberg: A visit with Zeiss Ikon's practical prodigy. Popular Photography, 65, no. 5 (November 1969): 88-89, 154.

Neumann, S. (1957). Prof. Emanuel Goldberg. Bulletin of the Research Council of Israel. Section C: Technology, 5C, no. 4: iii-v.

us patent 1915993


Michael Buckland: Vom Mikrofilm zur Wissensmaschine: Emanuel Goldberg zwischen Medientechnik und Politik. Avinus-Verlag, Berlin 2010, ISBN 978-3-86938-015-5, (Forschung visuelle Kultur; Bd. 1); dt. Übersetzung von: Emanuel Goldberg and his Knowledge Machine. Information, Invention, and political Forces. Libraries Unlimited, Westport CT u. a. 2006,


Buckland, Emanuel Goldberg and His Knowledge Machine : Information, Invention, and Political Forces
    - Microdots (105--118)
    - Television (148--)
    - The Statistical Machine (147--163)
    - The Microfilm Rapid Selector (217--228)
    - Bibliography of Emanuel Goldberg’s Writings (325--340)


On February 14, 1925, Klemperer morosely recorded his attendance at a university dinner the previous evening.


Opposite me, speaking Galician German, a Professor Goldberg, director of the ICA works (photographic company). At first we were embarrassed by his strict positivism—one will calculate psyche as an electrical current—but then he spoke most interestingly about progress in microphotography and the assured future of libraries. Already one can place 10,000 print pages in easily legible microscopic writing on the diameter of a dinner plate. One will carry a whole library in a briefcase. There will be microscopes in the reading rooms and one will find a particular page by turning a crank.

“Opposite me” Klemperer (1996, 11–12: “Mir gegenüber, galizisches Deutsch sprechend, ein Professor Goldberg, Director der Ica-Werke (photograph.-Unternehmen). Er war erst peinlich durch sein eng positivistisches Wesen—man werde Psyche berechnen lernen wie elektrischen Strom—erzählte dann höchst interessant von Forstchritten der verkleinerungsphotographie u. von der sicheren Zukunft der Bibliotheken. Man bringe heute schon 10 000 Druckseiten in gut lesbarer mikropscopischer Schrift auf dem Durchmesser eines frühstückstellers unter. Man wird eine Bibliothek in der brieftasche tragen. In den Lesesälen werden Mikroscope stehen, man wird durch Kurbeln die betreffenden Seiten einstellen.” Other references to Goldberg on p. 347 (“Geradezu galizisch”), 423–24, and 443–44. Klemperer’s later diaries (1995; English translation 1998) for 1933–45 mention Zeiss Ikon but not Goldberg.





Elsewhere, Otlet picked up on Ostwald’s notion that a dynamic, hypertextual encyclopedia would be, in effect, an artificial extension of the brain, and he speculated:

. . . that all knowledge, all information could be so condensed that it could even be contained in a limited number of works placed on a desk, and so within hand’s reach, and indexed in such a way as to make consultation very easy. In this way the World described in the entirety of the books would really be within everyone’s grasp. The Universal Book created from all the books would become very approximately an annex to the brain, a support for memory, an external mechanism and instrument of the mind, but so close to it, and so suited to its use that it would be truly be a sort of added organ, an attachment outside the skin. . . . The organ would have the function of rendering our Being in all places and all times.


. . . that all knowledge Otlet (1934b, 428); in English, Otlet (1990, 1): “Une hypothèse moins absolue, mais très radicale encore, supposerait que toutes les connaissances, toutes les informations pourraient être rendues assez compactes pour être contenues en un certain nombres d’ouvrages disposés sur la table de Travail même, donc à distance de la main, et indexés de manière à rendre la consultation aisée au maximum. Dans ce cas le Monde décrit dans l’ensemble des Livres serait réellement à portée de chacun. Le Livre Universel formé de tous les Livres, serait devenu très approximativement une annexe du Cerveau, substratum lui-même de la mémoire, méchanisme et instrument extérieur à l’esprit, mais si près de lui et si apte à son usage que ce serait vraiment une sorte d’organe annexe, appendice exodermique. . . . Cet organe aurait fonction de rendre notre être ‘ubique et éternel’.”





## valery, paul

https://www.idref.fr/027174484

```
%%%%%%%%%%%%%%%%%%%%

https://aaaaarg.fail/thing/51c5856f6c3a0e090c940e00

The Conquest of Ubiquity
Paul Valery , Paul Valéry


from "aesthetics", volume 13 of the collected works of paul valery, trans. ralph manheim. "la conquête de l'ubiquité" first published in "de la musique avant toute chose" (éditions du tambourinaire), 1928; in "pièces sur l'art" (1934); see "oeuvres II, pléiade" (1960); tr. anon as "on music", "the commonweal" (oct 15, 1930).

%%%%%%%%%%%%%%%%%%%%

https://aaaaarg.fail/thing/51c5856f6c3a0e090c0c0b00

Art and Progress
Paul Valery , Paul Valéry


Essay from 1930 published in the Yale Review. Republished text of Valéry's six page essay originally published in the Yale Review, 1930.


%%%%%%%%%%%%%%%%%%%%

Valéry, Paul. "Discours du centenaire de la photographie", in Etudes Photographiques, 10, November 2001, Paris : Société Française de Photographie, 89-106.
–––––– Cahiers I et II. Paris: Gallimard, Bibliothèque de la Pléiade, 1973, 1974.
–––––– Pièces sur l'Art. Paris: Gallimard, 1934.
------ Introduction à la Méthode de Leonard de Vinci. Paris: Gallimard, 1964.




Paul Valéry, « Discours du centenaire de la photographie », Études photographiques, 10 | Novembre 2001, [En ligne], mis en ligne le 10 septembre 2008. URL : http://journals.openedition.org/etudesphotographiques/265. consulté le 01 avril 2019.



VALERY, PAUL, „Discours du centenaire de la photographie", in : Etudes photographiques, 10, 2001, S. 89-96 [zuerst in: Bulletin de la Societe francaise de photographie, 3, 1939, pp. 71-78.]


Etudes photographiques / Société Française de Photographie
Paris 1.1996-35 (2017) ; damit Erscheinen eingestellt


Berlin SMB KunstB	 Link to library information [BER, DE-B11]

Shelfmark
Per 8/914
Holdings
1.1996 - 35.2017
Interlibrary loan
yes, copy only
```

#### valery-conquete-ref.txt

- De la musique avant toute chose, Paris: Edition du Tambourinaire 1929
https://catalogue.bnf.fr/ark:/12148/cb333370656
https://catalogue.bnf.fr/ark:/12148/cb31521227m
https://catalogue.bnf.fr/ark:/12148/cb43351216m
https://catalogue.bnf.fr/ark:/12148/cb347846410
https://catalogue.bnf.fr/ark:/12148/cb35882075g

- Nouvelles Littéraires (28. März 1931) https://gallica.bnf.fr/ark:/12148/bpt6k6452015m

- Roland Kayser, Die Eroberung der Allgegenwärtigkeit, in: Neue Deutsche Rundschau 42.1 (1931), pp. 713f.

- Pièces sur l'art, Paris: Gallimard 1934
- Über Kunst : Essays / Paul Valéry. Dt. von Carlo Schmid. Berlin; Frankfurt a.M.: Suhrkamp  1959


#### valery-mes-theatres-ref.txt


13529620X :  Mes théâtres (extraits) [Texte imprimé] / Paul Valéry / [S. l.] : W. Fischer , [1932]
135296161 :  Mes théâtres [Texte imprimé] / Paul Valéry / Paris : A. Michel , 1945
013334999 :  Cahiers Paul Valéry / Paris : Gallimard , 1975-
    --> Vol. 2: Mes théâtres / Paris: Gallimard , 1977

- La NEF, n° 6, mai 1945 [160 p.] # 2.jahrgang
Paul Valéry, Mes théâtres
www.revues-litteraires.com/articles.php?pg=1373
https://catalogue.bnf.fr/ark:/12148/cb34529822w
https://zdb-katalog.de/title.xhtml?idn=011193026



Paul Valéry, « Mes théâtres », dans Les Dernières nouvelles, Alger, 19 novembre 1942, Œuvres, Paris, La Pléiade, tome I, 1960.


Les dernières nouvelles à Alger le soir
https://lccn.loc.gov/sn95058048


## vernadskij, vladimir

```
Wladimir Iwanowitsch Wernadski

Vladimir Ivanovich Vernadsky, Khimicheskoje strojenije biosfery zemli i ee okruzhenija [Der chemische Aufbau der Biosphäre der Erde und ihre Umgebung], Moscow: Nauka 1965.

Vladimir Ivanovich Vernadsky, Nauchnaja mysl’ kak planetnoje javlenije [Der wissenschaftliche Gedanke als planetare Erscheinung], Moskau: Nauka 1991.

Vladimir Ivanovich Vernadsky, Scientific thought as a planetary phenomenon, Moscow Nongovernmental Ecological V. I. Vernadsky Foundation 1997.

Vladimir Vernadskij, »The biosphere and the noosphere«, in: American Scientist 33 (1945), Nr.1, pp. 1-12. (http://www.jstor.org/stable/27826043)

Vladimir I. Vernadskij: Der Mensch in der Biosphäre. Zur Naturgeschichte der Vernunft, Wolfgang Hofkirchner (ed.), Frankfurt/M/ Berlin/ Bern/ New York/ Paris/ Wien: Lang 1997.


Neskolko slow o noosfere, in: Uspechi biologii 18 (1944) 2, 113-120 (in: In : Biosfera. Moskwa 1967.)


Nauchnaja mysl’ kak planetnoje javlenije
Научная мысль как планетное явление
Der wissenschaftliche Gedanke als planetare Erscheinung

Khimicheskoje strojenije biosfery zemli i ee okruzhenija
Химическое строение биосферы Земли и ее окружения
Der chemische Aufbau der Biosphäre der Erde und ihre Umgebung


Der russische Geologe Wladimir Iwanowitsch Wernadski nutzte seinen Terminus erst wieder ab 1937, am ausführlichsten in der Arbeit Der wissenschaftliche Gedanke als planetare Erscheinung (Научная мысль как планетное явление). Dieser Artikel sollte Teil seines großen Lebenswerkes Der chemische Aufbau der Biosphäre der Erde und ihre Umgebung (Химическое строение биосферы Земли и ее окружения) werden.

„In den Jahren 1922 und 1923 nahm ich in meinen Vorlesungen an der Sorbonne in Paris als Grundlage der Biosphäre biogeochemische Erscheinungen an ... Von meiner biogeochemischen Grundlage der Biosphäre ausgehend, führte der französische Mathematiker und Philosoph, der Bergsonianer E. Le Roy in seinen Vorlesungen am College de France in Paris 1927 den Begriff ‚Noosphäre‘ als das moderne Stadium, das die Biosphäre geologisch durchlebt, ein. Er betonte dabei, zu dieser Vorstellung sei er zusammen mit seinem Freund, dem bedeutenden Geologen und Paläontologen Teilhard de Chardin gelangt“ (Vernadskij, Der Mensch in der Biosphäre, p. 11)
```

## virilio, paul

```
Paul Virilio "The Overexposed City" "La ville surexposee," from L'espace critique ( Paris: Christian Bourgeois, 1984); translated in Zone 1-2 (New York: Urzone, 1986)

ZONE 1 / 2
(ZONE) (MAU, BRUCE). Crary, Jonathan, Michel Feher, Hal Foster & Sanford Kwinter, Editors
Published by Urzone Inc. & Johns Hopkins University Press, 1986
ISBN 10: 0942299221 / ISBN 13: 9780942299229

1. Zone 1/2: The [Contemporary] City

Michel Feher; Sanford Kwinter; Jonathan Crary
Published by Zone Books, U.S.A. (1987)
ISBN 10: 0942299221 ISBN 13: 9780942299229

Zone gibt es in der Kunstbibliothek (Berlin)

L'espace critique in der FU

Change international auch in der FU, sonst TU
```

## turing, alan

- Turing  A.: Kann  eine  Maschine  denken? .-  In: Kursbuch 8, Hans M. Enzensberger (Hrsg.), 1967, S. 106-138.

## tesla, nikola

#### tesla-bib.txt

```
Nikola Tesla, Seine Werke, Bd.4: Energieübertragung und Radiotechnik, Peiting: Michaels-Verl. 1997.

Ulrich Heerd (Hrsg.): Nikola Tesla. Sein Werk (nur eigene Aufzeichnungen) 6 Bde. Edition Tesla. Michaels-Verlag, Peiting 2002


W. Bernard Carlson: Tesla. Der Erfinder des elektrischen Zeitalters. 2. Auflage. FinanzBuch, München 2017, ISBN 978-3-95972-007-6. (Amerikanische Originalausgabe: Tesla. Inventor of the Electrical Age. Princeton University Press, Princeton 2013)


Slavko Bokšan, Nikola Tesla und sein Werk und die Entwicklung der Elektrotechnik, der Hochfrequenz- und Hochspannungstechnik und der Radiotechnik, Leipzig/ Wien/ New York: Deutscher Verlag für Jugend und Volk 1932.
```

#### tesla-div.txt

```
the problem of increasing human energie (sic)

Century Magazine (Jun. 1900)

Abb. Electrical Review (Nov. 1898)
```


#### tesla-links.txt

http://hello-earth.com/nikolatesla/nikolatesla.html
http://www.tfcbooks.com/tesla/contents.htm


## sutherland, ivan

- Ivan Sutherland, »A head-mounted three dimensional display«, in: Proceedings of the Joint Computer Conference, 1968, 33, pp. 757-64.

- Ivan Sutherland, »The ultimate display«, in Proceedings of the International Federation of Information Processing Congress 1965, pp. 506-508.

## stickel, gerhard

- [@sti37.aut64.ger]
- [@sti37.aut66.ger]


```
- Gerhard Stickel, Automatische Textzerlegung und Registerherstellung. Darmstadt: Deutsches Rechenzentrum, 1964 (= Programm-Information 11). `sti37.aut64.ger`

- Gerhard Stickel, Monte-Carlo-Texte, in: Frieder Nake [et al.], Herstellung von zeichnerischen Darstellungen, Tonfolgen und Texten mit elektronischen Rechenanlangen, Darmstadt: Deutsches Rechenzentrum 1966 (= Programm-Information 21), pp. 43-51.

- Gerhard Stickel / Manfred Gräfe, Automatische Textzerlegung und Herstellung von Zettelregistern für das Goethe-Wörterbuch, in: Sprache im technischen Zeitalter 19 (1966), pp. 247-257. `sti37.aut66.ger`

- Gerhard Stickel, Monte-Carlo-Texte. Automatische Manipulation von sprachlichen Einheiten (1967), in: Exakte Ästhetik. Methoden und Ergebnisse empirischer und experimenteller Ästhetik. Bd. 5: Kunst aus dem Computer, Stuttgart: Nadolski, 1967, pp. 53-57.

- Gerhard Stickel, ›Computer-Dichtung‹. Zur Erzeugung von Texten mit Hilfe von datenverarbeitenden Anlagen, in: Der Deutschunterricht 18 (1966), H. 2, pp. 120-125.
```

## pynchon, thomas

"New York Times" ("Is It O.K. to Be a Luddite?")

## piscator, erwin

```
Erwin Piscator: Zeittheater. Das politische Theater und weitere Schriften. 1915–1966. Ausgewählt und bearbeitet von Manfred Brauneck und Peter Stertz. Rowohlt, Reinbek bei Hamburg 1986

Maria Ley-Piscator, The Piscator Experiment. The Political Theatre, Carbondale/ILL 1970. (50f. - Gründung des Dramatic Workshop)

Thomas George Evans: Piscator in the American Theatre. New York, 1939-1951. Ann Arbor: University of Wisconsin Press 1968.

Thea Kirfel-Lenk: Erwin Piscator im Exil in den USA 1939-1951. Berlin: Henschel 1984.

Claus-Dieter Krohn: Erwin Piscators Theaterarbeit in New York 1939-1951. In: Exil. Literatur und die Künste nach 1933. Hrsg. von Alexander Stephan. Bonn: Bouvier 1990, S. 154-170.

Gerhard F. Probst: Erwin Piscator and the American Theatre. New York, San Francisco, Berne etc.: Peter Lang 1991.

Ilka Saal: Broadway and The Depoliticization of Epic Theatre: The Case of Erwin Piscator. In: J. Chris Westgate (ed.): Brecht. Broadway and United States Theatre. Newcastle: Cambridge Scholars 2007, pp. 45–71.

John Willett: Erwin Piscator: New York and the Dramatic Workshop 1939–1951. Performing Arts Journal, Vol. 2, No.3 (1978), pp. 3–16.
```

## pichler, michalis

```
Michalis Pichler, The Work of Art in the Age of Digital Reproduction, in: Annette Gilbert / Clemens Krümmel (eds.), Thirteen Years: The Materialization of Ideas from 2002 to 2015 [Michalis Pichler], New York: Printed Matter, Inc./ Leipzig: Spector Books 2015.
```

## panofsky

- *Original und Faksimilereproduktion*, in *Der Kreis. Zeitschrift für künstlerische Kultur* 7 (1930)

## ostwald, wilhelm

http://www.tuhh.de/b/hapke/ostwald.htm

## nelson, ted

```
ted nelson replacing the printed word

Replacing the Printed [Written??] Word: A Complete Literary System, Lavington, Simon H., : Information Processing: Proceedings of the 1980 IFIP World Computer Congress , 8, 1013-1023.

Nelson TH (1980) Replacing the printed word: a complete literary system. In: Information pro- cessing 80: proceedings of IFIP Congress 80: Tokyo, Japan October 6–9, 1980, Melbourne,. Australia October 14–17, 1980, 1013–23.

Simon H. Lavington (Ed.): Information Processing 80, Proceedings of IFIP Congress 80, Tokyo, Japan - October 6-9, 1980 and Melbourne, Australia - October 14-17, 1980. North-Holland/IFIP, 1980, ISBN 0-444-86034-7
```


```
Proceedings of the American Documentation Institute
1965 Ted Nelson Hypertext

IN PRINT: Life, Love, College, Etc., 1959.
IN PRINT: Computer Lib/Dream Machines, 1974.  Microsoft edition, 1987.
  Original 1974 edition now reprinted from negatives.
The Home Computer Revolution, 1977.  Translated also into Japanese and Swedish.
Literary Machines (classic edition), 1981.  Literary Machines Technical Edition, 1987 et seq.
Selected Papers, ca. 1987.
The Future of Information.  (Published in Japan.)
IN PRINT: Geeks Bearing Gifts: How the Computer World Got This Way, 2008.
IN PRINT: POSSIPLEX (autobiography), 2010.
IN PRINT: The Scene Machine, 2014.
```

#### links

https://archive.org/details/SelectedPapers1977
http://libgen.is/book/index.php?md5=384ECDE91915D17FD906DFBE5DE002F2

## mosher, mike

```
Mike Mosher has painted and organized over a dozen public murals in San Francisco 1980-1990. Currently faculty of the San Francisco State University Conceptual Design and Information Arts Program, he has taught at the SFSU Inter-Arts Center and SFSU Multimedia Studies Program, University of San Francisco Professional Studies Program, and Cañada College in Redwood City CA. His 1994 essay "Towards Community Art Machines" in the online publication BAD SUBJECTS will appear in the anthology Bad Subjects (NYU Press, scheduled November 1997). Mike has also designed multimedia for Apple Computer, IBM Almaden Research Center, Cisco Systems and other Silicon Valley companies.
```

[src](http://bad.eserver.org/issues/1995/18/)


## moretti, franco

```
Moretti, Franco (2000), »Conjectures on World Literature«, in: New Left Review, 1, S. 54-68.
Moretti, Franco (2009), Kurven, Karten, Stammbäume: Abstrakte Modelle für die Literaturgeschichte, Frankfurt a.M.: Suhrkamp.
```

## calvin, mooers


```
mooers, wikipedia

He coined the term "information retrieval" using it first in a conference paper presented in March 1950.[1] See also a short paper published later that year from Mooers.

Mooers, C. (March 1950). "The theory of digital handling of non-numerical information and its implications to machine economics". Proceedings of the meeting of the Association for Computing Machinery at Rutgers University.

Mooers, C. (1950). "Information retrieval viewed as temporal signaling" (PDF). Proceedings of the International Congress of Mathematicians. Vol. 1, S.572-573.

Mooers received the American Society for Information Science's Award of Merit in 1978. The citation reads in part:

He was a participant in early developmental work on digital computers, a researcher, author, and implementer of applications in information retrieval; and a prophet in the 1950s describing the future importance of what is now called computer networks and distributive processing, and daring to predict that machines could simulate thought processes in retrieving computerized information. In 1947, he proposed the Zator, an electronic, film-scanning retrieval machine, and made the first proposal to use the Boolean operations or, and, and not to prescribe selections in retrieval machines. He developed his own Zatocoding System in 1948 using superimposed subject codes on edge-notched cards. He coined the term "Information Retrieval" in 1950, and went on from there to obtain several patents in information retrieval and signaling, produce a text-handling language (TRAC), author some 200 publications, and form one of the first companies whose only concern was information. His thinking has affected all who are in the field of Information and his early ideas are now incorporated into today's reality.
```


```
Mooers, Calvin N. (1946), »This is an inquiry into the future of mankind« in: Calvin N. Mooers Papers (CBI 81), Box 6, Folder 21, Charles Babbage Institute, University of Minnesota, Minneapolis.
Mooers, Calvin N. (1950a), »Information Retrieval Viewed as Temporal Signalling«, in: Proceedings of the International Congress of Mathematicians, 1, S. 572-573.
Mooers, Calvin N. (1950b), »The Theory of Digital Handling of Non-Numerical Information and its Implications to Machine Economics« in: Calvin N. Mooers Papers (CBI 81), Box 21, Folder 11, Charles Babbage Institute, University of
Minnesota, Minneapolis.
Mooers, Calvin N. (1960), »The Next Twenty Years in Information Retrieval«, in: American Documentation, 11, 3, S. 229-236.
Mooers, Calvin N. (2001), »The Computer Project at the Naval Ordnance Laboratory«, in: IEEE Annals of the History of Computing, 23, 2, S. 51-67.
```

## meryon, charles

xxx

## mendelsohn, erich

- *Amerika. Bilder eines Architekten* (1926)

## mosso, leonardo

- Programmierte Architektur (1969)

## malraux, andré

- Walter Grasskamp, *André Malraux und das imaginäre Museum. Die Weltkunst im Salon*. München: C. H. Beck 2014.


- Jens Schröter, *Archiv – post/fotografisch*
    - [Das Archiv der Kunst – das imaginäre Museum](http://www.medienkunstnetz.de/themen/foto_byte/archiv_post_fotografisch/4/)

```
Die Reproduktion von ›Kunstwerken‹ wurde von Anbeginn an als mögliches Betätigungsfeld der Fotografie gesehen. So hatten einige der frühesten Versuche zur Entwicklung der Fotografie durch Nicephore Niépce schon der Reproduktion von bereits existierenden Bildern gedient (vgl. Susanne Holschbach: »bFoto/Byte. Kontinuitäten und Differenzen zwischen fotografischer und postfotografischer Medialität«, den Abschnitt Technische Reproduzierbarkeit). Auch in »The Pencil of Nature« von Talbot waren schon zwei Fotografien von einer Büste enthalten. Die Folgen dieser Entwicklung können kaum hoch genug eingestuft werden: Wie bereits Walter Benjamin betont hat, ist die im 19. Jahrhundert und auch 20. Jahrhundert immer wieder diskutierte

Frage, ob die Fotografie (und später der Film) eine Kunst sei, zweitrangig gegenüber derjenigen danach, »ob nicht durch die Erfindung der Photographie der Gesamtcharakter der Kunst sich verändert habe«. [16] Eine zweite, damit eng verbundene Frage ist, wie das entsprechende fotografische Archiv das Wissen von der Kunst(geschichte) restrukturiert.

Einige Konsequenzen dieser Transformation hat der ehemalige französische Kulturminister André Malraux in seinem 1951 erschienenen Buch »Les Voix du Silence« im indirekten Anschluss an Heinrich Wölfflin, Daniel Henry Kahnweiler und Walter Benjamin wirkmächtig formuliert. Seine Bezeichnung des durch fotografische Reproduktionen eröffneten Feldes als ›imaginäres Museum‹ wurde weithin bekannt. Malrauxs Museum ist imaginär, weil es nicht an einen Ort gebunden ist: Die fotografische Reproduktion zwingt nicht nur »zu einer Auseinandersetzung mit allen Ausdrucksmöglichkeiten der Welt […]« [17] – wie das Museum, sondern überschreitet jenes noch, weil es auch Kunstwerke enthalten kann, die an (unverrückbare) Architektur gebunden sind – wie zum Beispiel Fresken. Zudem mussten Kunstkenner zuvor herumreisen, um die Werke zu vergleichen – ein Vergleich zwischen Bild und Erinnerungsbild, der laut Malraux eine »gewisse Zone der Unbestimmtheit« herbeiführte. Demgegenüber stünden heutzutage dem Studierenden eine Fülle farbiger Reproduktionen nach den meisten Hauptwerken zur Verfügung. [18]

Die fotografische Reproduktion (und die damit einhergehende Diaprojektion) erlaubt also, Werke aus verschiedensten Zeiten nebeneinander auf einem Tableau zu präsentieren. Sie klammert anfänglich die Farbe aus – und lenkt so die Konzentration noch einmal auf das disegno. Außerdem vereinheitlicht sie die reproduzierten Objekte in der Größe – das Foto der Cheops-Pyramiden erscheint neben einem Foto einer Buchminiatur auf einer Buchseite –, reiht Fragmente beziehungsweise Detailausschnitte nebeneinander und diese wieder neben ganze Bilder und bringt so – je nach Kontext – »eine gewisse Verwandtschaft […] voneinander sonst noch so weit entfernte[r] Darstellungsobjekte zustande«. [19] So entsteht – sehr vereinfacht gesagt – die Kunstgeschichte als eine »Kunst der Fiktion« [20] , das heißt als ein Archiv intervisueller Relationen. Auch die doppelte

Diaprojektion hat so im 19. Jahrhundert, trotz gewisser Anlaufschwierigkeiten, die kunstgeschichtliche Lehre einschneidend verändert. [21] Es entstand die von Wölfflin spätestens seit 1915 so genannte Stilgeschichte – insofern qua Diaprojektion die visuellen Differenzen zwischen Bildern evident werden konnten. [22] Die Kunstgeschichte ist so zu einer »Geschichte des Photographierbaren« [23] geworden. Wie weit diese Formulierung einmal reichen würde, war Malraux bei dieser Zuspitzung seiner Überlegungen wohl noch nicht bewusst: Zahlreiche Kunstformen – wie die Performance, die Land Art, das Happening, die Prozesskunst etc. [24] –, die sich in ihrem Rekurs auf das Flüchtige und Verzeitlichte der Strategie einer systematischen Ephemerisierung bedienen, wären ohne ihre fotografische oder filmische Dokumentation überhaupt nicht als Gegenstand von Kunstgeschichte denkbar.

[16] Walter Benjamin, »Das Kunstwerk im Zeitalter seiner technischen Reproduzierbarkeit« [zweite Fassung], in: ders., Gesammelte Schriften, hg. v. Rolf Tiedemann; Hermann Schweppenhäuser, Frankfurt a. M. 1980, Bd. I.2 (S. 471–508), S. 486.
horizontal dividing line
[17] André Malraux, Das imaginäre Museum, Genf 1947, S. 8. Diese erste deutschsprachige Auflage enthält, anders als die verbreitete Edition von 1987 bei Campus, die Fotos aus dem französischen Original. Zum Kontext Malraux’ vgl. Rosalind Krauss, »Das Schicksalsministerium«, in: Wolf, Paradigma Fotografie (S. 389–398).
[18] Vgl. André Malraux, Das imaginäre Museum, S. 9.
horizontal dividing line
[19] André Malraux, Das imaginäre Museum, S. 16.
horizontal dividing line
[20] André Malraux, Das imaginäre Museum, S. 19.
horizontal dividing line
[21] Vgl. Heinrich Dilly, »Die Bildwerfer. 121 Jahre kunstwissenschaftliche Dia-Projektion« [1994], in: Kai-Uwe Hemken (Hg.), Im Bann der Medien. Texte zur virtuellen Ästhetik in Kunst und Kultur. CD-ROM, Weimar 1997.
horizontal dividing line
[22] Vgl. Heinrich Wöfflin, Kunstgeschichtliche Grundbegriffe, München 1915, S. 13–31 zum Begriff des Stils. Zu Malrauxs These, dass die Subsumtion unter den Parameter des Stils ein Effekt des ›imaginären Museums‹ ist, vgl. André Malraux, Das imaginäre Museum, S. 12.
horizontal dividing line
[23] André Malraux, Das imaginäre Museum, S. 24.
horizontal dividing line
[24] Zu diesen Einsätzen der Fotografie gibt es eine breite Literatur, siehe jüngst den Ausstellungskatalog The Last Picture Show. Artists Using Photography 1960-1982, Douglas Fogle (Hg.), Minneapolis 2003.
```


## ramon, lull

- [@wol68.kun29.ger]


Beschreibung der von ihm entworfenen Maschine unter anderem in:

```
Werner Künzel, Lullistische Begriffsmaschinen, in Michael Cahn (ed.), Der Druck des Wissens. Geschichte und Medium der wissenschaftlichen Publikation, Wiesbaden: Reichert 1991, pp. 15–16.
```

Hegel spricht mehrfach über Lullus und seine *ars magna*.

## lissitzky, el

```
"Unser Buch", in Gutenberg Jahrbuch 1927, ed. Alois Ruppel, Mainz: Gutenberg-Gesellschaft, 1926-27. (German)

El Lissitzky, “Our Book,” in El Lissitzky: Life, Letters, Text, ed. Sophie Lissitzky-Küppers, trans. Helene Aldwinckle and Mary Whittall, Thames and Hudson, Ltd., London 1968.

"The Future of the Book", New Left Review 41, Jan-Feb 1967, pp 39-44; repr. in Communication and Class Struggle, 2: Liberation, Socialism, eds. Armand Mattelart and Seth Siegelaub, New York: International General, and France: International Mass Media Research Center, 1983, pp 267-269. (English)

"Our Book", trans. Helene Aldwinckle and Mary Whittall, in Lissitzky-Küppers, El Lissitzky, 1968, pp 360-363; repr. in Graphic Design Theory: Readings From the Field, ed. Helen Armstrong, Princeton, 2009, pp 25-31. (English)
```


## lem, stanislaw

### books

- *Summa Technologiae*

The book has 8 chapters, each dealing with far-fetched implications of a certain concept: ... The first edition also contained: 9 Art and Technology (Polish: Sztuka i technologia.) After Leszek Kołakowski severely criticised the chapter, it was removed in later editions, both Polish and foreign. In 1988 Lem remarked that during the time past the subject had gained it its actuality. [src](https://en.wikipedia.org/wiki/Summa_Technologiae)

- Stanisław Lem, *Summa Technologiae*, Kraków: Wydawnictwo Literackie 1964.
    - Aus dem Polnischen von Friedrich Griese.
        - Frankfurt am Main: Insel 1978
        - Berlin: Volk und Welt 1980

## leary, timothy

- [Chaos und Cyber-Kultur](https://archive.org/details/chaosundcyberkul00learrich) (1997)

### links

- [timothy leary archives](http://www.timothylearyarchives.org)


## laßwitz, kurd

- [@las48.uni04.ger]
    - `ENG` The Universal Library, in: Clifton Fadiman (ed.), Fantasia Mathematica, New York: Simon and Schuster, pp. 237-243.


- *Der Gehirnspiegel. Ein Triumph der Technik*, in: *Die Woche* 1 (1900), Nr. 13.
    - Nie und Immer. Bd. 2: Traumkristalle. Neue Märchen. Stark vermehrte Aufl. Leipzig 1907, pp. 97-108.
        - [DNB](http://d-nb.info/574562621)


Beim Gehirnspiegel handelt es sich um ein Gerät, mit dessen Hilfe sich das Gehirn durchleuchten und photographieren lässt.



## kretschmann, karl friedrich

- Scarron am Fenster, in: W.G. Becker. (ed.), Almanach und Taschenbuch zum geselligen Vergnügen. Leipzig 1798, S 64-90 und 1799, S 42-80,
- Scarron am Fenster, in: W.G. Becker (ed.), Taschenbuch zum geselligen Vergnügen. Leipzig: Gleditsch 1798, S 64-90.
- Scarron abermals am Fenster, in: W.G. Becker (ed.), Almanach und Taschenbuch zum geselligen Vergnügen, Leipzig: Voß 1799, pp. 42-80.

## korn, arthur

```

KORN A., "Uber ein Apparat zue Herstellung von Elektrischen Fernphotographien", Elektronische Zeitschrift, XXIII, 1902
A. KORN, Elektrische Fernsehphotographie und Ahnliches, Verlag von S. Hirzel, Leipzig, 1904

KORN, A. und GLATZEL, Br., Handbuch der Phototelegraphie und Telautographie, Verlag von Nemich, Leipzig, 1911.
KORN, A. und NESPER, A., Bildrundfunk, Julius Pringer, Berlin, 1926.
KORN A., Elektrisches Fernsehen, Verlag Otto Salle, Berlin, 1930.

```

## king, stephan

- *Word Processors of the Gods*
    - `DEU` *Taste des Todes. Der Textcomputer der Götter*, Playboy 11/1984
    - `FRA` *L’Ordinateur des dieux*


- *Tales from the Darkside*
    - Season 1, Episode 8: *Word Processors of the Gods*


## kelly, kevin

- [Kevin Kelly and Jerry Kaplan - A Future with Intelligent Machines](https://youtu.be/a4LPIexd_Ak)
- [Kevin Kelly: The next 5,000 days of the web](https://youtu.be/yDYCf4ONh5M)


## kawano, hiroshi

```
Hiroshi Kawano. The Philosopher at the Computer
Fri, 23.09.2011 6 pm, ZKM_Foyer

The Japanese philosopher, Hiroshi Kawano (*1925), is one of the most important pioneers in
the conquest of computer technology for the arts. With the exhibition Hiroshi Kawano. The
Philosopher at the Computer the ZKM is dedicating a first retrospective to his work. The
exhibition comprises numerous works and documents which have never before been
presented outside Japan, and draws on the rich Hiroshi-Kawano archive located at the ZKM
since 2010. The retrospective emphasizes Kawano's special role in the circle of pioneers in
»computer art«: he was neither artist, who discovered the computer as a new production
medium and theme, nor engineer who came to art via the new machine, but a philosopher,
who left his desk for the computer center to experiment with theoretical models.

```


## kafka, franz

*Kafka kennt sich in Amerika nicht aus*, 99 Fundstücke, [franzkafka.de](http://www.franzkafka.de/franzkafka/fundstueck_archiv/fundstueck/1121411)

Es ist charakteristisch für Kafkas erzählerische Prosa, dass örtliche und zeitliche Bestimmungen zumeist unscharf bleiben und der Leser daher unter dem Eindruck steht, alles spiele sich in einem gespenstischen Zwischenreich, einem Nirgendwo ab – wie im Traum. So wird niemals der Name der Stadt genannt, in der sich Der Process vollzieht, und auch das Dorf am Fuß des Schlosses bleibt namenlos.

Die einzige bedeutsame Ausnahme von dieser Regel ist der 1912/13 entstandene Roman Der Verschollene. Obwohl Kafka die USA nur aus Reisebüchern, Vorträgen und mündlichen Berichten kannte, hatte er sich dennoch vorgenommen, »das allermodernste New Jork« zu schildern, wie er gegenüber seinem Verleger Kurt Wolff bekannte. Daher sind viele Örtlichkeiten korrekt benannt, und bemerkenswerterweise ist Der Verschollene auch der einzige erzählerische Text Kafkas, in dem ausdrücklich von Prag die Rede ist.

Um so auffallender, dass Kafka im Manuskript dieses Romans einige sonderbare Irrtümer unterliefen. Offenbar machte er sich bei seinen Recherchen keine systematischen Notizen, sondern verließ sich auf sein Gedächtnis: So kam es, dass er etwa eine wiederholt falsche Schreibweise aus Arthur Holitschers sozialkritischer Reportage Amerika – heute und morgen übernahm und »Oklahama« anstelle von »Oklahoma« schrieb. Auch ist von einer Brücke die Rede, »die New York mit Boston verbindet« – wobei Kafka natürlich die von zahlreichen Abbildungen bekannte Brooklyn Bridge vor Augen hatte. Schließlich verlegte er San Francisco auf die falsche Seite des Kontinents: Sein Protagonist Karl Rossmann wird zu einer Reise nach »Frisco« genötigt, da für ihn »die Erwerbsmöglichkeiten im Osten viel bessere« seien.

Die erstaunlichste und offenbar gewollte Abweichung seiner Romanwelt von der Wirklichkeit findet sich indessen schon im allerersten Absatz: Die Freiheitsstatue, die alle New York-Reisenden begrüßt, reckt hier keine Fackel, sondern ein Schwert in den Himmel. Da dieses Kapitel des Verschollenen separat unter dem Titel Der Heizer (1913) veröffentlicht wurde, fiel der krasse ›Fehler‹ auch Freunden und Kritikern auf, so dass Kafka Gelegenheit gehabt hätte, den Text in den späteren, neu gesetzten Auflagen zu korrigieren. Er unterließ es.

Quellen: Brief an Kurt Wolff, 25. Mai 1913, in: Franz Kafka, Briefe 1913–1914, Frankfurt am Main (S.Fischer) 1999, S. 196f. Franz Kafka, Der Verschollene, Frankfurt am Main (S.Fischer) 1983, S. 124, 144 u. 387.

Fotos: George Grantham Bain Collection, Library of Congress, Washington, D.C. – Arthur Holitscher, Amerika – heute und morgen, Berlin (S.Fischer) 1912, S. 367.




Kafka wrote in The Man who Disappeared (America) »Everyone is welcome! Anyone who wants to become an artist should apply! We are the theater that can use everyone, a place for everyone!«, New York: Oxford University Press, 2012, p. 195.

M. Mcluhan in his text »The Brain and the Media: The ›Western‹ Hemisphere«, published in December 1978



- [digbib.org](http://www.digbib.org/Franz_Kafka_1883/)


```

    PDF: Amerika
    PDF: Aphorismen
    PDF: Auf der Galerie
    PDF: Blumfeld, ein aelterer Junggeselle
    PDF: Brief an den Vater
    PDF: Das Schloss
    PDF: Das Urteil
    PDF: Der Bau
    PDF: Der Gruftwaechter
    PDF: Der Prozess
    PDF: Die Verwandlung
    PDF: Erzaehlungen
    PDF: In der Strafkolonie
    PDF: Kleine Fabel
    PDF: Verschiedenes

```

## hayles, n. katherine

- wiki, en: [selected bibliography](https://en.wikipedia.org/wiki/N._Katherine_Hayles#Selected_bibliography)

## čapek, karel

- R.U.R. Rossum’s Universal Robots (1920)

[wiki](https://en.wikipedia.org/wiki/R.U.R.)

R.U.R. is a 1920 science fiction play by the Czech writer Karel Čapek. R.U.R. stands for Rossumovi Univerzální Roboti (Rossum's Universal Robots). However, the English phrase "Rossum's Universal Robots" had been used as the subtitle in the Czech original. It premiered on 25 January 1921 and introduced the word "robot" to the English language and to science fiction as a whole.

R.U.R. quickly became influential after its publication. By 1923, it had been translated into thirty languages.


## gunzenhäuser, rul


- Mathematik und Dichtung. Versuche zur Frage einer exakten Literaturwissenschaft. Nymphenburger Verlagshandlung, 1967

- Rul Gunzenhäuser, Ein Weihnachtsgedicht
  - wohl in Ja und Nein. Unabhängige Jugendzeitschrift (1960), Nr. 12 und (1961), Nr. 1

- Helmar Frank / Rul Gunzenhäuser, Über Mime und Pantomime, in: Grundlagenstudien. Aus Kybernetik und Geisteswissenschaft 1 (Okt. 1960), No. 4, pp. 113-121

- Rul Gunzenhäuser, Abschließende Mitteilung über ein Programm zur Erzeugung stochastisch-logistischer Texte, in: Grundlagenstudien. Aus Kybernetik und Geisteswissenschaft 1 (Okt. 1960), No. 4, pp. 127-128.

- Rul Gunzenhäuser, Zur mathematischen Textanalyse: Der Vergleich von Texten, in: Grundlagenstudien. Aus Kybernetik und Geisteswissenschaft 1 (Dez. 1960), No. 5, pp. 153-159.

- Rul Gunzenhäuser, Bericht über ein Programm zur numerischen Textanalyse, in: Grundlagenstudien. Aus Kybernetik und Geisteswissenschaft 2 (Jul. 1961), No. 2, pp. 51-55.

- Rul Gunzenhäuser, Programmierung des Schönen [Rezension], in: Grundlagenstudien. Aus Kybernetik und Geisteswissenschaft 2 (Jul. 1961), No. 2, pp. 51-55.

- Rul Gunzenhäuser, Zur Synthese von Texten mit Hilfe programmgesteuerter Ziffernrechenanlagen, in: mtw. Zeitschrift für moderne Rechentechnik und Automation 10 (1963), No. 1, pp 4-9.


## gernsback, hugo

- *The Isolator*, Science and Invention. Vol. 13 No. 3. New York: Experimenter Publishing Company. July 1925. 201-296.
- Paul O'Neil, »The Amazing Hugo Gernsback. Prophet of Science. Barnum of the Space Age«, in: Life Magazine (26 Juli 1963), pp. 62-68.
    - [google books](https://books.google.de/books?id=JlIEAAAAMBAJ&lpg=PP1&pg=PA62#v=onepage&q&f=false)

```
Gernsback shows off a pair of ›teleyeglasses‹, an idea he first dreamed up in 1936, for which he feels the world is now ready. (LIFE (Jul 26, 1963) p. 68)
```

[src](https://books.google.de/books?id=JlIEAAAAMBAJ&lpg=PP1&pg=PA68#v=onepage&q&f=false)


## gates, bill

### text

- *Der Weg nach vorn. Die Zukunft der Informationsgesellschaft* (1995)

### video

- [The Road Ahead - Bill Gates Comdex Keynote 1995](https://youtu.be/o0O0Xjpjvfc)
- [Bill Gates - COMDEX 1990 (Complete Presentation)](https://youtu.be/uGA1Chm_8RE)

## englisch, paul

- Paul Englisch: Plagiat! Plagiat! Eine Rundschau, Berlin 1930.
    - http://visuallibrary.net/116481

- Debora Weber-Wulff, False Feathers: A Perspective on Academic Plagiarism, 2014
    - https://books.google.de/books?isbn=3642399614


```
The jurist and writer Paul Englisch (1887–1935) was sued in 1929 by the publisher Georg Socher.
```

## engels, friedrich

- Die Lage der arbeitenden Klasse in England. Nach eigner Anschauung und authentischen Quellen, Leipzig: Otto Wigand 1845.

## doehl, reinhard

- Sprache und Elektronik. Über neue technische Möglichkeiten, Literatur zu erstellen und zu rezipieren.
    - WDR, Kulturelles Wort, 27.2.1970.
    - Übernahme: SDR, Studio für neue Literatur, 31.7.1970

## dahl, roald

- *The Great Automatic Grammatizator*, in: *Someone Like You*
    - New York: Knopf 1953
    - London ; Secker & Warburg ; 1954 ; 256 S.


deutsch als:

- *Und noch ein Küßchen! Weitere ungewöhnliche Geschichten*. Aus d. Amerik. übertr. v. Hans-Heinrich Wellmann
    - Hamburg ; Rowohlt ; 1963 ; 235 S.
        - Grimm / VW
    - Stuttgart ; Hamburg : Deutscher Bücherbund [1966]
        - DNB

## coetzee, j. m.

- Coetzee, Brief an Paul Auster

- Colin Marshall, When J.M. Coetzee Secretly Programmed Computers to Write Poetry in the 1960s, url: http://www.openculture.com/2017/07/when-j-m-coetzee-secretly-programmed-computers-to-write-poetry-in-the-1960s.html

```
Before J.M. Coetzee became perhaps the most acclaimed novelist alive, he worked as a programer. That may not sound particularly notable these days, but bear in mind that the Nobel laureate and two-time Booker-winning author ... held that day job first at IBM in the early 1960s — back, in other words, when nobody had a computer on their desk. And back when IBM was IBM: that mighty American corporation had brought the kind of computing power it alone could command to branch offices in cities around the world, including London, where Coetzee landed after leaving his native South Africa after graduating from the University of Cape Town.
```

- Rebecca Roach, The computer poetry of J. M. Coetzee's early programming career (June 28, 2017), url: https://blog.hrc.utexas.edu/2017/06/28/the-computer-poetry-of-j-m-coetzees-early-programming-career/

```
Coetzee’s global reputation rests on his literary output, for which he received a Nobel Prize in 2003. Before he embarked on a career as a scholar and writer, the South African–born writer was a computer programmer in the early years of the industry’s development (1962–1965).

In the mid 1960s Coetzee was working on one of the most advanced programming projects in Britain. During the day he helped to design the Atlas 2 supercomputer destined for the United Kingdom’s Atomic Energy Research Establishment at Aldermaston. At night he used this hugely powerful machine of the Cold War to write simple “computer poetry,” that is, he wrote programs for a computer that used an algorithm to select words from a set vocabulary and create repetitive lines. Coetzee never published these results, but edited and included phrases from them in poetry that he did publish.
[In 'Youth' heißt es, die Gedichte wurden in Südafrika veröffentlicht.]

Excitingly, I also was able to examine Coetzee’s born-digital materials, recovered from 5.25” and 3.5” floppy diskettes. This was invaluable, and enabled me to begin to establish a timeline of what kinds of computing hardware and software Coetzee was employing across his writing career.
```

## churchland, paul

```
Paul M. Churchland, Die Seelenmaschine. Eine philosophische Reise ins Gehirn, Heidelberg; Berlin; Oxford: Sepktrum, Akad. Verl. 1997.

ders., The Engine of Reason, the Seat of the Soul. A Philosophical Journey into the Brain, Cambridge/MA: The MIT Press 1995
```

## balázs, béla

- Die Kunstphilosophie des Films (1938)
    - Das Wort

## babbage, charles

- On the Economy of Machinery and Manufactures (1832)
    - [monoskop](https://monoskop.org/images/a/a1/Babbage_Charles_On_the_Economy_of_Machinery_and_Manufactures.pdf)
    - [archive.org](https://archive.org/details/oneconomyofmachi00babbrich)
- Traité sur économie des machines et des manufactures (1833)
    - [bnf](https://gallica.bnf.fr/ark:/12148/bpt6k85754p)
    - [archive.org](https://archive.org/details/traitsurlconomi00babbgoog)
- Babbage’s Calculating Engines. Being a Collection of Papers Relating to Them (1889)
    - [monoskop](https://monoskop.org/images/4/40/Babbage_Charles_Calculating_Engines.pdf)

## apollinaire, guillaume

- Les flaneurs des deux rives (1918)
- Calligrammes (1918)
    - Il pleut

## asimov, isaac

- Foundation, Astounding Science-Fiction 29 (May 1942), No. 3, pp. 38-53.
- Visit to the World's Fair of 2014 (Aug 16, 1964), [New York Times](https://archive.nytimes.com/www.nytimes.com/books/97/03/23/lifetimes/asi-v-fair.html)
- Futuredays: A Nineteenth Century Vision of the Year 2000. New York: Henry Holt 1986.

- [A Vision for the Future](https://youtu.be/V4Ux83nJC0U) (1992)

## assmann, aleida

- Erinnerungsräume. Formen und Wandlungen des kulturellen Gedächtnisses (1999)
- Cultural Memory and Western Civilization: functions, media, archives (2011)

## tauschek, gustav

- Reading Machine (1932) Patent


- Martin Helfert, Christoph M. Wintersteiger: Gustav Tauschek's Punchcard Accounting Machines, Proceedings of the Workshop on Methodic and Didactic Challenges of the History of Informatics (MEDICHI 2007), OCG 220, Austrian Computer Society, 2007.

## franke, herbert w.

Art as Data Processing


## calvino, italo

die unsichtbaren städte

## arendt, hannah

```
Hannah Arendt in New York
Dokumentation, Deutschland 2006, Erstausstrahlung
Regie: Jean-Claude Lubtchansky


Hannah Arendt

Hinweis auf Walter Benjamin
(Regarding Walter Benjamin)
Goethe House, New York

16 January 1968

mit uni-lpz-zugang:
http://search.alexanderstreet.com/view/work/1827079

```

- Helgard Mahrdt, ''Unausrottbar ist das Poetische solange es noch das Wundern gibt', Hannah Arendt über Walter Benjamin, in Dichterisch denken. Hannah Arendt und die Künste, ed. Wolfgang Heuer, Irmela von der Lühe, Göttingen 2007.

## benjamin, walter

- Walter Benjamins kleine Bestie, in: Der Freitag
- Jewish Museum NY, Arcades Ausstellung (2017)

## blumenberg, hans

Hans Blumenberg, Eine imaginäre Universalbibliothek, in: Akzente 28 (1981), H. 1, pp. 27-40.

Hans Blumenberg, Die Lesbarkeit der Welt, Frankfurt/M: Suhrkamp 1981 (Kap. X: Weltchronik oder Weltformel, pp. 121–149)

## berners-lee, tim

Tim Berners-Lee, et al, "World-Wide Web: Information Universe”, Electronic : Research, Applications and Policy, April 1992.

Berners-Lee, T.J, Cailliau, R., and Groff, J-F, "The World-Wide Web", Computer Networks and ISDN Systems 25 (1992) 454-459. North-Holland

Tim Berners-Lee and Cailliau, R., CERN, "The World-Wide Web", in proceedings of the conference "Computing in High Energy Physics", Annecy, France, 1992. Yellow report, CERN, Geneva, Switzerland.

Tim Berners-Lee, et al, “The World Wide Web,”Communications of the ACM, August, 1994.

Tim Berners-Lee, “WWW: Past, Present, and Future”, IEEE, Computer Magazine, Vol. 29, No. 10, Oct. 1996.

Tim Berners-Lee, “Europe And the Info Age,” Time Magazine, Winter 1996


Tim Berners-Lee, “World-Wide Computer”, Communications of the ACM, Vol. 40, No. 2, Feb. 1997.

Tim Berners-Lee, “Spinning the Web: A place for everything, and everything on the Web?”, Data Communications, Vol. 26, No. 14, Oct. 1997.

Tim Berners-Lee and James Hendler "Publishing on the Semantic Web", Nature, April 26 2001 p. 1023-1025.

Tim Berners-Lee, James Hendler and Ora Lassila, "The Semantic Web", Scientific American, May 2001, p. 29-37.

## bell, gordon

[i am data](http://image.slidesharecdn.com/mylifebits-van-microsoft-23154/95/mylifebits-van-microsoft-7-728.jpg)

[ppt](http://research.microsoft.com/en-us/um/people/gbell/Bell_MyLifeBits_Alpbach_0408.ppt)

- Digital memories in an era of ubiquitous computing and abundant storage. Von Mary Czerwinski et al. in: Communications of the ACM, Bd. 49, Nr. 1, S. 44, Januar 2006

- MyLifeBits: a personal database for every­thing. Von Jim Gemmell, Gordon Bell und Roger Lueder in: Communications of the ACM, Bd. 49, Nr. 1, S. 88, Januar 2006

- A personal digital store. Von Gordon Bell in: Communications of the ACM, Bd. 44, Nr. 1, S. 86, Januar 2001



## flusser, vilém

- *Gedächtnisse*, in: Ars Electronica (ed.), *Philosophien der neuen Technologie*, Berlin: Merve 1989, pp. 41-56.
- *Die Schrift. Hat Schreiben Zukunft?*, Göttingen: Immatrix, 1987.
    - [pub](http://equivalence.com/labor/lab_vf_edi.shtml)
    - [extract](http://equivalence.com/labor/lab_vf_exz_schrift.shtml)


## nora, pierre


- Pierre Nora, «Entre mémoire et histoire», in Les Lieux de mémoire, tome 1, La République, Gallimard, Paris, 1984, p. XIX.

- Pierre Nora, «Entre mémoire et histoire» [1984], in Les Lieux de mémoire, tome 1, La République, Gallimard, Paris, 1997, pp. 23-43.

- *Zwischen Geschichte und Gedächtnis: Die Gedächtnisorte*, in: *Zwischen Gedächtnis und Geschichte*. Aus dem Fanzösischen von Wolfgang Kaiser, Berlin: Wagenbach 1990, pp. 11-33. [dnb](http://d-nb.info/910445842)

- *Zwischen Geschichte und Gedächtnis: Die Gedächtnisorte*, in: *Zwischen Geschichte und Gedächtnis*. Aus dem Fanzösischen von Wolfgang Kaiser. Ungekürzte Ausg., Frankfurt am Main: Fischer 1998, pp. 11-42. [dnb](http://d-nb.info/95428092X)


#### desc

- [memory](03-desc.Rmd#memory)


## jean paul


`Die Taschenbibliothek`

Es kann sein, daß meine jungen Leser zufrieden sind, wenn sie meine Erzählung gelesen; aber dankbar werden sie sein nach zwanzig Jahren, wenn sie sie benutzet haben.


*Taschenkalender zur belehrenden Unterhaltung für die Jugend und ihre Freunde a. d. J. 1797*



## leibniz, g. w.

### Apokatastasis panton



Gottfried Wilhelm Leibniz, De l'horizon de la doctrine humaine (1693). Apokatastasis pantōn (1715). Textes inédits, trad. et annotés par Michel Fichant. Paris : Libr. Philosophique Vrin, 1991

Fichant, Michel (Herausgeber)

http://d-nb.info/944868193

G.W. Leibniz, Mysterion apokatastaseos panton. Petersen, J.W., Frankfurt am Main, 1700
Monatlicher Auszug aus allerhand neu herausgegebenen, nützlichen und artigen Büchern Aprilis MDCCI (= April 1701), pp. 1-37.
(Zu finden bey Nicol. Förstern/Buchhändl. in Hanover.)

https://books.google.de/books?id=xwlUAAAAcAAJ&pg=RA3-PA13#v=onepage&q&f=false
http://resolver.sub.uni-goettingen.de/purl?PPN55651341X_1701

wiederabgedruckt:
Gottschalk Eduard Guhrauer (ed.), Leibnitz's Deutsche Schriften, Vol. II, Berlin: Veit und Comp 1840, pp. 342--347.

https://archive.org/details/bub_gb_c4ARAAAAYAAJ/
https://archive.org/details/bub_gb_c4ARAAAAYAAJ/page/n357


Der Verfasser dieses Werks will sich in der Vorrede auf diejenige Apokatastasis pantone gründen, deren der Apostel Petrus Act. 3. erwähnet. (342)


http://www.gelehrte-journale.de/startseite/id/00028338X/#tx_find


zu Förster: https://data.cerl.org/thesaurus/cnp01876233


### links

- [History of Computers and Computing, Dreamers, Gottfried Leibniz](http://history-computer.com/Dreamers/Leibniz.html)



### resources

- [Aufzeichnungen von Leibniz zur Rechenmaschine](http://digitale-sammlungen.gwlb.de/index.php?id=6&no_cache=1&tx_dlf%5Bid%5D=449&tx_dlf%5Bpage%5D=1&tx_dlf%5Bpointer%5D=0)
- [G. W. Leibniz resources - Helsinki.FI](https://www.mv.helsinki.fi/home/mroinila/texts.htm)



## otlet, paul

- Mundaneum

### misc

- Paul Otlet, *Traité de Documentation. Le livre sur le livre. Théorie et pratique*, Brüssel 1934.
- Paul Otlet, *Monde. Essai d'Universalisme*, Brüssel: Van Keerberghen 1935 ( = Editiones Mundaneum 1 ).


- *International Organisation and Dissemination of Knowledge. Selected Essays of Paul Otlet*, Warden Boyd Rayward (ed.), Amsterdam/ New York: Elsevier 1990.


- Bernd Stickfort, *Das Internet als enzyklopädische Utopie*, In: Ingrid Tomkowiak (Hrsg.): Populäre Enzyklopädien. Von der Auswahl, Ordnung und Vermittlung des Wissens. Chronos, Zürich 2002, S. 271-290. (Darin über Otlet und das papierne Internet)
- Hilmar Schmundt, *Vater der Zettelsuchmaschine*, in: Der Spiegel (2008), Nr. 26, p. 140.
- Meike Laaf, *Googles genialer Urahn*, in: Spiegel Online (2011), url: 'http://www.spiegel.de/netzwelt/web/netzvisionaer-paul-otlet-googles-genialer-urahn-a-768312.html', 12/2015.
- Lena Christolova, *Das Mundaneum oder das papierne Internet von Paul Otlet und Henri La Fontaine*, in: Stefan Böhme, Rolf F. Nohr, Serjoscha Wiemer (eds), Sortieren, Sammeln, Suchen, Spielen. Die Datenbank als mediale Praxis, Münster: Lit 2012, pp. 31-54.
- Frank Hartmann, *Einleitung. Die Logik der Datenbank. Zwischen Leibniz und Google – Otlet der 'Weltbibliothekar'*, in: ders. (ed.), Vom Buch zur Datenbank. Paul Otlets Utopie der Wissensvisualisierung, Berlin: Avinus 2012 (= Forschung Visuelle Kultur 2), pp. 11-61.
- Frank Hartmann, *Paul Otlets Hypermedium. Dokumentation als Gegenidee zur Bibliothek*, in: LIBREAS. Library Ideas, 28 (2015). http://libreas.eu/ausgabe28/04hartmann/


### desc

- [library photo](#)



## binkley, robert

### read

- Vernon D. Tate, *From Binkley to Bush*, The American Archivist, Vol. 10, No. 3 (Jul., 1947), pp. 249-257
- Rick Prelinger, *Points of Origin: Discovering Ourselves through Access*, in: The Moving Image: The Journal of the Association of Moving Image Archivists, Vol. 9, No. 2 (FALL 2009), pp. 164-175
- George Veletsianos; Royce Kimmons, *Networked Participatory Scholarship: Emergent techno-cultural pressures toward open and digital scholarship in online networks*, in: Computers & Education 58 (2012), pp. 766–774. [doi](http://dx.doi.org/10.1016/j.compedu.2011.10.001)


## bush, vannevar


```
(1945a) »As we may think.« In: Atlantic Monthly 176, S. 101-108.
(1945b) As we may think. A top U.S. scientist forsees a possible future world in which man-made machines will start to think. In: Life. 10.Sept., 19 (11), 1945, S.112-124.
(1945c) Science, the Endless Frontier. A Report to the President on a Program for Postwar Scientific Research, July 1945. Washington, National Science Foundation 1960. (1946) As we may think. In: V.B.: Endless Horizons. Washington, D.C. 1946, S.16-38. (1967) Memex Revisited. In: VB. Science Is Not Enough. New York 1967, S.75-101. (1970) Pieces of the Action. London 1972.

The Paradoxical Memex The original text of “As we may think”
is in Bush (1945a; 1945b; and various reprints). Associate Press
issued a news release and Time printed a news item (Machine
1945). Nyce and Kahn (1991) is a useful, though rather uncritical,
resource for “As We May Think;” also Nyce and Kahn
(1989).

From Memex to Hypertext: Vannevar Bush and the Mind's Machine (James M. Nyce and Paul Kahn, Academic Press, 1991

Vannevar Bush, Mechanization and the Record, Fortune, 1939 (??)
```


## fidler, roger

### read

- *»Videotex services will become mature businesses...«*, in: *The Changing Newspaper. Year 2000* / *Newspapers in the Year 2000*, New York: Associated Press, Fall 1981 (= Associated Press Managing Editors Special Report) [wc](http://www.worldcat.org/oclc/10589458) [wc_alt_1](http://www.worldcat.org/oclc/27399461) [wc_alt_2](http://www.worldcat.org/oclc/29716719) [wc_alt_3](http://www.worldcat.org/oclc/20767076)
- *Plugging into the News*, in: *Newspapers Design 2000 and Beyond*, Reson, VA: American Press Institute 1988, pp. 36--41. [wc](http://www.worldcat.org/oclc/21124343) --> nur in Dänemark und Spanien verfügbar
- *Mediamorphosis, or the Transformation of Newspapers into a New Medium*, in: *Media Studies Journal* (Fall 1991) --> SBB
- bf., *Die Zeitung der Zukunft kommt ohne Papier aus*, in: FAZ (Mittwoch, Jul. 20, 1994), Nr. 166, p. 18.
- *Declaration of Roger Fidler in Support of Samsung’s Opposition to Apple’s Motion for Preliminary Injunction* (2011)


### video

- The Tablet Newspaper: A Vision for the Future (1994)



### div

- Garrison, *Selected bibliography: computerization and the newsroom* (1983) [src](https://doi.org/10.1080/02560054.1983.9652916)
- William D. Rineheart, *Will there be newspapers in the year 2000?*, Vidura, 23(2) Apr. 1986, p, 72-5.

- Dokument vom Gerichtsprozess Apple vs. Samsung(?) wg. Tablet (2011)

## lutz, theo

### open

- Theo Lutz, *Die Grundlagen der Datenverarbeitung. Der Computer und seine Möglichkeiten. Lerntext*, Berlin: IBM 1981.
    - 1981, 1st ed., [albertina](https://katalog.ub.uni-leipzig.de/Record/0001761689)
    - 1987, 2nd ed., [dnb](http://d-nb.info/945776179)


- Theo Lutz, *Computer ohne Geheimnis : e. Einf. in d. Informationsverarbeitung* (1983)
    - [dnb](http://d-nb.info/871515172)


- *Ein Blick in die Zukunft : das IBM Personal System/2, Stuttgart: IBM Deutschland 1987*
    - [wc](http://www.worldcat.org/oclc/255425979)

- Detlef Borchers, *Computerjahr 2010: Die Zukunft, die nicht geschehen ist*, FAZ ([Jan 2, 2010](https://www.faz.net/-gqz-14xmp))

```
Prognosen gibt es viele, wenn es um die Zukunft des Computers und des Internets geht. Aus der Vielzahl der Vorhersagen ragt eine Arbeit des Computerherstellers IBM aus dem Jahr 1987 heraus. Zehn Thesen für 2010 wagte man dort, die sich als erstaunlich hellsichtig erweisen.

Technischer Chefredakteur der Studie war Theo Lutz, ein Schüler des Kybernetikers Max Bense (dessen hundertster Geburtstag im Februar 2010 mit einem großen Kongress über „Weltprogrammierung“ gefeiert wird). Lutz hatte schon in den fünfziger Jahren Computerpoesie auf einem Zuse-Rechner programmiert. Aus seinem Namen entstand das schöne Verb „lutzen“ als Ausdruck für die Tätigkeit von Computern „stochastische poetische Texte“ aus Prosa zu generieren. So wurde Kafkas Schloss mit einem Computer zu einem Gedicht gelutzt, die entsprechenden Programme findet man heute noch im Netz.
```

## fried, alfred hermann

[en, wiki](https://en.wikipedia.org/wiki/Alfred_Hermann_Fried)

Born	11 November 1864
Vienna, Austria-Hungary

Died	5 May 1921 (aged 56)
Vienna

archive.org
https://archive.org/search.php?query=creator%3A%22Fried%2C+Alfred+Hermann%2C+1864-1921%22

HathiTrust
https://catalog.hathitrust.org/Search/Home?lookfor=%22Fried,%20Alfred%20Hermann%22&type=author&inst=



Annuaire de la vie internationale... / par Alfred H. Fried
https://gallica.bnf.fr/ark:/12148/cb326966804/
https://gallica.bnf.fr/ark:/12148/cb326966804/date.item
https://catalog.hathitrust.org/Record/000524653
https://catalog.hathitrust.org/Record/011712389

1905
https://gallica.bnf.fr/ark:/12148/bpt6k57277351

1906
https://gallica.bnf.fr/ark:/12148/bpt6k5688624m

1907
https://gallica.bnf.fr/ark:/12148/bpt6k5652035n


Union des associations internationales
https://data.bnf.fr/fr/11990201/union_des_associations_internationales/



Lexikon deutscher citate. Hrsg. von Alfred Hermann Fried. Leipzig, P. Reclam jun. [1889]
https://catalog.hathitrust.org/Record/001901239/Home

Lexicon fremdsprachlicher citate / hrsg. von Alfred Hermann Fried. Leipzig : Philipp Reclam, [1888]
https://catalog.hathitrust.org/Record/100906336/Home

Die Landläufigsten Citate und berühmsten Aussprüche in deutscher, lateinischer, französischer, englischer und italienischer Sprache by Fried, Alfred Hermann, 1864-1921
Publication date 1900
https://archive.org/details/dielandlufigst00frieuoft/
